apiVersion: apps/v1
kind: Deployment
metadata:
  name: house-price-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: house-price-app
  template:
    metadata:
      labels:
        app: house-price-app
    spec:
      containers:
      - name: streamlit
        image: house-price-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: house-price-service
spec:
  type: LoadBalancer
  selector:
    app: house-price-app
  ports:
  - port: 80
    targetPort: 8501
