# .github/workflows/mlops.yml
name: MLOps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest flake8

      - name: Lint
        run: flake8 src tests

      - name: Run tests
        run: pytest tests/

  # docker-deploy:
  #   needs: build-test
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}

  #     - name: Build and push image
  #       run: |
  #         docker build -t ${{ secrets.DOCKER_USERNAME }}/house-price-app:latest .
  #         docker push ${{ secrets.DOCKER_USERNAME }}/house-price-app:latest

  #     - name: Deploy to Kubernetes
  #       uses: appleboy/ssh-action@v1
  #       with:
  #         host: ${{ secrets.REMOTE_HOST }}
  #         username: ${{ secrets.REMOTE_USER }}
  #         key: ${{ secrets.REMOTE_KEY }}
  #         script: |
  #           kubectl apply -f k8s-deployment.yaml
